### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by olegantonyan** [clio/polymorphic_integer_type#55]
Is it already in progress? I had to change few things to make it work (kind of, not perfectly). But maybe a proper support is around the corner.

Also, a bit related, is there a chance for this PR to be merged? https://github.com/clio/polymorphic_integer_type/pull/53

**Comment by psdao1102** [comment]
@olegantonyan hey, do you know what needs to be changed? Im in a pickle because of this gem not being updated to 7. Id like to fork and make the changes myself but i don't understand the inner workings of active record.

**Comment by olegantonyan** [comment]
I use own fork https://github.com/olegantonyan/polymorphic_integer_type
You can see the diff here https://github.com/clio/polymorphic_integer_type/compare/master...olegantonyan:polymorphic_integer_type:ruby-3-and-rails-7-support

But there is a problem with has_one association. Don't remember the details exactly, but I had to work around it. So if you end up going this route - test it thoroughly

**Comment by cmrd-senya** [comment]
Rails 7 has been supported since v3.2.0. However Rails 7.1 is not supported, the gemspec explicitly restricts the package to depend on Rails 7.0 and below.

@wendy-clio are there any plans to support Rails 7.1 ? What's the main issue with supporting Rails 7.1?

Rails 7.2 will be released soon too

**Comment by cmrd-senya** [comment]
@wendy-clio thanks for the update!

We might work on the support ourselves once we get close to upgrading from Rails 7.0 to 7.1, if it's not done by then. But I cannot yet tell regarding when we can get there.

If we prepare a PR for supporting Rails 7.1, can we expect it to be reviewed and accepted?

Is there anything special we may need to know to work on that?

**Comment by cmrd-senya** [comment]
Hello @wendy-clio !

I made some research on Rails 7.1 support with `polymorphic_integer_type` gem.

Here's what I've found.

There's one test that fails once Rails is set to 7.1 version.

Here's the test that fails:

```

Failures:

  1) PolymorphicIntegerType When a link is created through an association and the link is accessed through the associations should have the proper source
     Failure/Error: expect(source.source_links[0].source).to eql source
     
       expected: #<Animal id: 1, name: "Alexi", type: nil, kind: "Cat", owner_id: nil>
            got: nil
     
       (compared using eql?)
     # ./spec/polymorphic_integer_type_spec.rb:182:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:42:in `block (3 levels) in <top (required)>'
     # /home/senya/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
     # /home/senya/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
     # /home/senya/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
     # /home/senya/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
     # /home/senya/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:212:in `transaction'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'

Finished in 4.21 seconds (files took 0.60888 seconds to load)
1 example, 1 failure
```

I've tracked down the change in Rails that is causing the failure.

The change is this line:
https://github.com/rails/rails/commit/7b6720dfc8d1606c0b3ed7c92b735180dcfa7e9d#diff-ceff30ddab4e756e3a70ece45076eb17ff2f587a068dae657d2ad3a265a3f0d6

![image](https://github.com/user-attachments/assets/a709754e-8d82-4eca-ac29-305d0d157b7d)

Previously what was happening is that in Rails during creation of the record with association assignment was used:
```
l['source_type'] = 'Animal'
```

Now it has been replaced with `_write_attribute`:
```
l._write_attribute('source_type', 'Animal')
```

![image](https://github.com/user-attachments/assets/c8fe518b-6973-4ebf-bd90-334f0eb180f4)

The result `l.source_type` of the former is "Animal" and the result of the latter is `nil`.

![image](https://github.com/user-attachments/assets/1214ea5e-e2c2-4839-8d4f-106557a61183)

@wendy-clio so I successfully tracked down the change that causes the tests to fail now.

However I'm still unsure on what we can do on the gem's side and what would we need to update in order to fix the gem and make it compatible with Rails 7.1.

@wendy-clio is there any suggestions you might provide on the potential fix? I assume you know more about about how the gem integrates with Rails.
